language: node_js
node_js:
  - "v12.8.0"
before_script:
  - npm install
script: npm run build
deploy:
  local-dir: dist/top-badass-front
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
notifications:
  email: false