language: node_js
node_js:
  - "v12.8.0"

dist: trusty
sudo: required

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules


before_script:
  - npm install -g @angular/cli

script: npm run build

deploy:
  local-dir: dist/top-badass-front
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
notifications:
  email: false